// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/15/2024, 9:51:35 PM
const configMerger = require("/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/plugins/**/*.{js,ts,mjs}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/composables/**/*.{js,ts,mjs}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/utils/**/*.{js,ts,mjs}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gr03a/yuu-dev/SecHack365_4C_enjo/frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
